// Live BBZ — browse the BBZ (Pio) range stores with seat -> line ->
// solution type -> depth ladder navigation, all inside the standard
// RangeBrowser. Three pages share this component, one per store
// (generated by straddle-solutions/scripts/bbz_to_store.py, wizard
// schema):
//   Live       bbz/store/       equal stacks — ChipEV + ICM stages
//   ICM asym   bbz/store-asym/   asymmetric full-table ICM stack configs
//   PKO        bbz/store-pko/    PKO stages with equal/$N bounty variants
// The stores keep class:freq strings (169 hand classes — the PioViewer
// paste shape, ~8x smaller than per-combo expansion); this page expands
// classes to concrete combos at load. The dev server serves bbz/ from
// straddle-solutions; the deploy ships a copy mirrored by the root
// `npm run sync-bbz` script into public/bbz/ (vite copies public/ into
// the build). The notice below only shows if the store is genuinely
// missing (bad checkout, stale mirror).
import { useEffect, useMemo, useState } from "react";
import { RangeBrowser } from "@poker/design-system/src/components/RangeBrowser";
import {
  materializeLine,
  type StoredRange,
} from "@poker/design-system/src/data/ranges";

type LineManifest = {
  title: string;
  types: { type: string; subtitle: string; stacks: number[] }[];
};

const bbzUrl = (rel: string) => new URL(`bbz/${rel}`, document.baseURI).toString();

const SEATS = ["UTG", "UTG+1", "LJ", "HJ", "CO", "BTN", "SB", "BB"] as const;
const SEAT_SLUG = {
  UTG: "utg", "UTG+1": "utg1", LJ: "lj", HJ: "hj",
  CO: "co", BTN: "btn", SB: "sb", BB: "bb",
} as const;

// line slugs group into the same three tables as the Live page, plus the
// limped line
const lineGroup = (line: string) =>
  line === "rfi"
    ? "RFI"
    : line.startsWith("vs-3bet-")
      ? "vs 3bet"
      : line === "vs-sb-limp"
        ? "limped"
        : "vs open";

const GROUP_ORDER = ["RFI", "vs open", "vs 3bet", "limped"];

const chip = (active: boolean) =>
  `px-2 py-1 rounded-md text-[11px] font-semibold cursor-pointer border transition-colors select-none whitespace-nowrap ${
    active
      ? "bg-accent text-dark border-accent"
      : "text-txt/80 bg-panel2/60 border-transparent hover:bg-panel2 hover:text-txt"
  }`;

const SUITS = ["s", "h", "d", "c"];
function combosOfClass(cls: string): string[] {
  if (cls.length === 2) {
    const r = cls[0];
    const out: string[] = [];
    for (let i = 0; i < SUITS.length; i++)
      for (let j = i + 1; j < SUITS.length; j++) out.push(r + SUITS[i] + r + SUITS[j]);
    return out;
  }
  const hi = cls[0], lo = cls[1], kind = cls[2];
  if (kind === "s") return SUITS.map((s) => hi + s + lo + s);
  const out: string[] = [];
  for (const a of SUITS) for (const b of SUITS) if (a !== b) out.push(hi + a + lo + b);
  return out;
}

// class:freq (AA:1,AKs:0.35) -> combo:freq (AsAd:1,...) — passes concrete
// combo tokens through untouched, so either store format loads
function expandActions(s: string): string {
  if (!s) return s;
  return s.split(",").map((t) => {
    const i = t.indexOf(":");
    const name = t.slice(0, i);
    if (name.length === 4) return t;
    const w = t.slice(i + 1);
    return combosOfClass(name).map((c) => `${c}:${w}`).join(",");
  }).join(",");
}

interface LiveBbzProps {
  /** store directory under bbz/ — 'store' | 'store-asym' | 'store-pko' */
  store: string;
  /** hash page prefix — 'live' | 'live-asym' | 'live-pko' */
  hash: string;
}

export function LiveBbzPage({ store, hash }: LiveBbzProps) {
  const [manifest, setManifest] = useState<Record<string, Record<string, LineManifest>> | null>(null);
  const [failed, setFailed] = useState(false);

  const [seat, setSeat] = useState<string>(() => {
    const s = window.location.hash.split("/")[1];
    return s && SEATS.includes(s as (typeof SEATS)[number]) ? s : "BB";
  });
  const slug = SEAT_SLUG[seat as keyof typeof SEAT_SLUG] ?? "bb";
  const lines = manifest?.[slug] ?? {};

  const [line, setLine] = useState<string>(() => window.location.hash.split("/")[2] ?? "");

  const [loading, setLoading] = useState(false);
  // line-file cache — refetch on a fresh dev session, never during browsing
  const cache = useMemo(() => new Map<string, StoredRange[]>(), []);

  useEffect(() => {
    fetch(bbzUrl(`${store}/index.json`))
      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
      .then(setManifest)
      .catch(() => setFailed(true));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [store]);

  // keep the line valid for the seat
  useEffect(() => {
    if (!manifest) return;
    const ls = Object.keys(lines);
    if (!ls.length) return;
    if (!line || !(line in lines)) setLine(ls[0]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [manifest, slug]);

  // load the line file when the selection changes
  useEffect(() => {
    if (!line || !(line in lines)) return;
    if (cache.has(`${slug}/${line}`)) return;
    setLoading(true);
    fetch(bbzUrl(`${store}/${slug}/${line}.json`))
      .then((r) => r.json())
      .then((d) => {
        for (const e of d.stacks ?? []) {
          for (const k of Object.keys(e.actions ?? {})) e.actions[k] = expandActions(e.actions[k]);
        }
        cache.set(`${slug}/${line}`, materializeLine(d, () => ""));
        setLoading(false);
      })
      .catch(() => {
        setFailed(true);
        setLoading(false);
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [manifest, slug, line]);

  const ranges = line ? cache.get(`${slug}/${line}`) : undefined;

  const pickSeat = (s: string) => {
    setSeat(s);
    const first = Object.keys(manifest?.[SEAT_SLUG[s as keyof typeof SEAT_SLUG]] ?? {})[0] ?? "";
    setLine(first);
    window.history.replaceState(
      null,
      "",
      `${window.location.pathname}${window.location.search}#${hash}/${encodeURIComponent(s)}/${first}`,
    );
  };

  const pickLine = (l: string) => {
    setLine(l);
    window.history.replaceState(
      null,
      "",
      `${window.location.pathname}${window.location.search}#${hash}/${encodeURIComponent(seat)}/${l}`,
    );
  };

  if (failed) {
    return (
      <div className="max-w-xl m-auto pt-16 text-center">
        <div className="text-lg font-bold text-txt pb-2">BBZ data not available</div>
        <div className="text-[13px] text-muted">
          The BBZ range store could not be loaded. Regenerate it with{" "}
          <code>straddle-solutions/scripts/bbz_to_store.py</code> and mirror it for the deploy
          with <code>npm run sync-bbz</code>.
        </div>
      </div>
    );
  }

  return (
    <div className="flex gap-5 items-stretch h-full min-h-0 [@media(max-width:760px)]:flex-col [@media(max-width:760px)]:h-auto [@media(max-width:760px)]:gap-3">
      <nav className="w-52 shrink-0 rounded-xl border border-line bg-panel pb-3 overflow-y-auto [@media(max-width:760px)]:w-full">
        <div className="px-2.5 pt-3 pb-1">
          <div className="text-[9.5px] uppercase tracking-widest text-muted/60 pb-1">Seat</div>
          <div className="flex flex-wrap gap-0.5">
            {SEATS.filter((s) => manifest && Object.keys(manifest[SEAT_SLUG[s]]).length).map((s) => (
              <button key={s} className={chip(seat === s)} onClick={() => pickSeat(s)}>
                {s}
              </button>
            ))}
          </div>
        </div>
        <div className="px-2.5 pt-3 pb-1">
          <div className="text-[9.5px] uppercase tracking-widest text-muted/60 pb-1">Line</div>
          {GROUP_ORDER.map((g) => {
            const ls = Object.keys(lines).filter((l) => lineGroup(l) === g);
            if (!ls.length) return null;
            return (
              <div key={g} className="pb-1.5">
                <div className="text-[9px] uppercase tracking-wider text-muted/40 pb-0.5">{g}</div>
                <div className="flex flex-wrap gap-0.5">
                  {ls.map((l) => (
                    <button key={l} className={chip(line === l)} onClick={() => pickLine(l)}>
                      {lines[l].title.replace(seat + " ", "")}
                    </button>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </nav>
      <div className="min-w-0 flex-1 flex flex-col min-h-0">
        {loading && !ranges && (
          <div className="text-[13px] text-muted pt-8 text-center">Loading range…</div>
        )}
        {ranges && (
          <RangeBrowser
            key={`${slug}-${line}`}
            ranges={ranges}
            hashPrefix={`#${hash}/${encodeURIComponent(seat)}/${line}`}
            postflop={false}
            fill
          />
        )}
      </div>
    </div>
  );
}

export function LiveEqualPage() {
  return <LiveBbzPage store="store" hash="live" />;
}
export function LiveAsymPage() {
  return <LiveBbzPage store="store-asym" hash="live-asym" />;
}
export function LivePkoPage() {
  return <LiveBbzPage store="store-pko" hash="live-pko" />;
}
